### ISSUE TITLE
uninitialized constant SitePrism when using without Rails

### ISSUE THREAD

**Issue by ssoleh** [site-prism/site_prism#5] opened 2019-07-02 13:08 UTC
When I use SitePrism with non rails, I can't inherit from SitePrism::Page.
On rails project this is working correctly, cause gems are loaded in spec_helper

Only workaround for this is not to require site-prism in spec helper and add in spec_helper: 
require 'bundler'
Bundler.require(:default)

OS: Ubuntu 16.04
SitePrism version - 3.3
Capybara version - 3.25.0

**Comment by luke-hill** [comment] 2019-07-02 13:26
Can you reproduce the issue in a small self-contained git repo and describe exactly what you are expecting to see / do see.

I use SitePrism in a multitude of non-rails projects (Both cucumber and otherwise), and it works fine.

From your original description, maybe you just need to do `require site_prism` but this isn't a bug here, its a feature of the ruby language.

**Comment by ssoleh** [comment] 2019-07-09 12:53
You can check in my open repo cent_regression, here are lines from spec helper.
require 'bundler'
Bundler.require(:default)
Dir['./spec/Page_Objects/*.rb'].each { |f| require f }

If I comment this and write require site_prism, it won't start. The thing is when I use pry and write SitePrism in console, everything is ok, but SitePrism::Page is uninitialized constant

**Comment by luke-hill** [comment] 2019-07-10 08:52
Again, I'm not going to try cobble code piecemeal.

Can you link me to a repo I can pull down and run `rspec` in or something that fails.

**Comment by ssoleh** [comment] 2019-07-10 08:57
https://github.com/ssoleh/cent_regression

**Comment by luke-hill** [comment] 2019-07-10 12:33
I'll have a little look.

**Comment by luke-hill** [comment] 2019-07-10 15:22
I've had a little investigation, but I didn't tweak much as there was no instructions.

I altered the Gemfile.lock to use `1.17.3` ran `bundle` and then ran `rspec`, and only got a warning about previously initialized constants. So I'm fairly confident this is an issue with your setup.

You mention it only works with `site_prism` only. I'm confused with how else you have been making the gem work?

Can you let me know if this is still an issue? I'm not saying there may not be clashes with the new gem (And I'm aware of these), but no-one has reported the issue I predicted they would, and this doesn't seem like it.

**Comment by luke-hill** [comment] 2019-07-10 15:23
EDIT: When passing instructions / further issues, can you refer to https://github.com/site-prism/site_prism#setup with regards to how to set it up.

**Comment by ssoleh** [comment] 2019-07-11 08:37
I suppose we can close this issue, because now it works, with require 'site_prism' in spec_helper.
According to your question, how I made gem work, was to add in spec_helper:

require 'bundler'
Bundler.require(:default)

instead of require 'site_prism'

**Comment by ssoleh** [comment] 2019-07-11 08:47
EDIT: Made some investigations, and removed gem site_prism-all_there, and received same uninitialized constant SitePrism as before, but also now I receive Gem::MissingSpecError: Could not find 'site_prism-all_there' as a warning message, I suppose siteprism gem has been updated with this "all_there" support gem. When I was implementing my project, this "all_there" gem wasn't created yet.

**Comment by luke-hill** [comment] 2019-07-11 09:04
Ok I'm truly lost because you keep going round in circles.

`site_prism` now has a dependency that I introduced recently of `site_prism-all_there` however this is currently not consumed or active in the codebase yet, it will be shortly.

There may have been a slight namespace conflict, however that's not what you're describing to me.

If you have an issue, can you please explain clearly how to *reproduce* it, failing that, close the issue.

**Comment by ssoleh** [comment] 2019-07-11 09:15
My main idea is that when I was building my project with Siteprism, this error occurred because this dependency was missing. But now I have rolled back to the initial state, and it is working, I suppose we can close this issue, there was something with my setup.

**Closed** 2019-07-11 09:15 UTC
Labels: Needs Investigation
